alias c="clear"
alias stesting="ssh desahe@hcudtesting"
alias skronos="ssh desarrollo@kronos"
alias sodoo="ssh desarrollo@odooclinica"
alias scaea="ssh developer@caea"
alias cd..='cd ..'
alias cd~='cd ~'
alias rodoo='sudo service odoo restart'
alias todoo='sh tail.sh'
